# Generated by Django 4.0.2 on 2022-03-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaprofile',
            name='url_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imgProfile/'),
        ),
    ]
